// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    [Migration("20260224121814_Changed cancellationTokens on dataseed")]
    partial class ChangedcancellationTokensondataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("DonorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodRequestId = 1,
                            CancellationToken = "cQE7UfT4h4k_mhain5VsHqWF5ifL2L3Zv6ZALCli5LY",
                            DonorId = 1,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 2,
                            BloodRequestId = 1,
                            CancellationToken = "cshs1Emd-D4Avux2tX2zOILZekO0NMHRS9EIJ1ptFCI",
                            DonorId = 2,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 3,
                            BloodRequestId = 4,
                            CancellationToken = "XFZB14bTQrZFp4zD6TokzORK3VVqap4GrI9uWVGP6YI",
                            DonorId = 3,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 4,
                            BloodRequestId = 2,
                            CancellationToken = "3-I5hOuZcqtA75zP5Jh6JX8V3C2EQCMxzxoUXVQC038",
                            DonorId = 4,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 5,
                            BloodRequestId = 2,
                            CancellationToken = "Hlhv3JdcKZu9qc--1rk1y_gZOTjDFoP1ZadNQVkxUu0",
                            DonorId = 5,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 6,
                            BloodRequestId = 3,
                            CancellationToken = "3e2NUbkKlyfSUP1RITdhbE--qYtf-PWnf6JqnxIs360",
                            DonorId = 1,
                            IsCancelled = true
                        },
                        new
                        {
                            Id = 7,
                            BloodRequestId = 8,
                            CancellationToken = "gakImI2b8f-LSS2qa_sG_AY_2B5aAwc-qBcGRbI_TzM",
                            DonorId = 2,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 8,
                            BloodRequestId = 10,
                            CancellationToken = "ZO6wS39Rlipx31y3nwCNxqhcivFTU6tn8OyHfFN20bU",
                            DonorId = 4,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 9,
                            BloodRequestId = 7,
                            CancellationToken = "jzXEPTZXtk1qjcGAqA1U5QG1TadefhrdUI_L_7ZuzOQ",
                            DonorId = 5,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 10,
                            BloodRequestId = 4,
                            CancellationToken = "mT_3jnFlWZubQ_udT2Wpd1cKSQeCzyKf8Jx11m3CJlM",
                            DonorId = 2,
                            IsCancelled = true
                        });
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("BloodTypesNeeded")
                        .HasColumnType("integer[]");

                    b.Property<int>("RemainingUnits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("BloodRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 7, 6 },
                            RemainingUnits = 3,
                            RequestDate = new DateTime(2026, 2, 26, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7946),
                            RequestStatus = 0,
                            RequesterId = 3,
                            TargetUnits = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 0 },
                            RemainingUnits = 0,
                            RequestDate = new DateTime(2026, 2, 23, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7961),
                            RequestStatus = 1,
                            RequesterId = 3,
                            TargetUnits = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Virasoro 1249, Rosario",
                            BloodTypesNeeded = new[] { 3, 5 },
                            RemainingUnits = 10,
                            RequestDate = new DateTime(2026, 3, 1, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7963),
                            RequestStatus = 0,
                            RequesterId = 4,
                            TargetUnits = 10
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bv. Oroño 860, Rosario",
                            BloodTypesNeeded = new[] { 6 },
                            RemainingUnits = 1,
                            RequestDate = new DateTime(2026, 2, 25, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7966),
                            RequestStatus = 0,
                            RequesterId = 5,
                            TargetUnits = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "San Luis 2450, Rosario",
                            BloodTypesNeeded = new[] { 1 },
                            RemainingUnits = 4,
                            RequestDate = new DateTime(2026, 3, 6, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7968),
                            RequestStatus = 0,
                            RequesterId = 7,
                            TargetUnits = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 7 },
                            RemainingUnits = 2,
                            RequestDate = new DateTime(2026, 2, 24, 17, 18, 13, 626, DateTimeKind.Utc).AddTicks(7970),
                            RequestStatus = 0,
                            RequesterId = 3,
                            TargetUnits = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "Virasoro 1249, Rosario",
                            BloodTypesNeeded = new[] { 2 },
                            RemainingUnits = 0,
                            RequestDate = new DateTime(2026, 2, 19, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7973),
                            RequestStatus = 1,
                            RequesterId = 4,
                            TargetUnits = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "Bv. Oroño 860, Rosario",
                            BloodTypesNeeded = new[] { 6, 0 },
                            RemainingUnits = 6,
                            RequestDate = new DateTime(2026, 2, 27, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7975),
                            RequestStatus = 0,
                            RequesterId = 5,
                            TargetUnits = 6
                        },
                        new
                        {
                            Id = 9,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 4 },
                            RemainingUnits = 8,
                            RequestDate = new DateTime(2026, 2, 14, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7977),
                            RequestStatus = 2,
                            RequesterId = 3,
                            TargetUnits = 8
                        },
                        new
                        {
                            Id = 10,
                            Address = "San Luis 2450, Rosario",
                            BloodTypesNeeded = new[] { 7 },
                            RemainingUnits = 2,
                            RequestDate = new DateTime(2026, 3, 11, 12, 18, 13, 626, DateTimeKind.Utc).AddTicks(7979),
                            RequestStatus = 0,
                            RequesterId = 7,
                            TargetUnits = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan.perez@example.com",
                            Name = "Juan Pérez",
                            Phone = "3411234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.garcia@example.com",
                            Name = "María García",
                            Phone = "3417654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.lopez@example.com",
                            Name = "Carlos López",
                            Phone = "1198765432"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.mtz@example.com",
                            Name = "Ana Martínez",
                            Phone = "3415554443"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lucia.f@example.com",
                            Name = "Lucía Fernández",
                            Phone = "3410009998"
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "heca@example.com",
                            IsActive = true,
                            Name = "Hospital Emergencias Clemente Álvarez",
                            Password = "$2a$11$wSFgXhiaTSRF57Ggw/zd.OI3pVQdpxhmpsclMzIwNAbs6SW7XV0K.",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "italiano@example.com",
                            IsActive = true,
                            Name = "Hospital Italiano",
                            Password = "$2a$11$OdfMdf96yzPXE4vjXQnt7.5tYIaZFYZYnahrPX0st9RGl7aHYMAAu",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "parque@example.com",
                            IsActive = true,
                            Name = "Sanatorio Parque",
                            Password = "$2a$11$3ZMjSzFhhGRuiULzkRn.HOokv8RvUOK0eQ5Sw7NINwoJodCtTijqm",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "centenario@example.com",
                            IsActive = true,
                            Name = "Hospital Centenario",
                            Password = "$2a$11$gHdgdHBM9ERDkQAM7.6nPe9zzAhRKbGAHS.bAq4/HB.yis1QNIA9K",
                            Role = "Requester",
                            AdmissionStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            Email = "clinica@example.com",
                            IsActive = true,
                            Name = "Clínica de la Mujer",
                            Password = "$2a$11$mHIgA8.OpHquLFtkReeEGer7kZQm7CHJfXpzbLc4WmzOb6iW6x4ZC",
                            Role = "Requester",
                            AdmissionStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Staff", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "Admin",
                            Password = "$2a$11$1MHAL7w8Nfx102.U4e6s4.9lWB96GN2fYDZa3uP6PXwLRy1lPiMmi",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mod@example.com",
                            IsActive = true,
                            Name = "Moderador",
                            Password = "$2a$11$Lg6qYokWCmymc1zt69INnuOykpwo7dFEqd0Grh/HkH6E9hLVVvRI2",
                            Role = "Moderator"
                        });
                });

            modelBuilder.Entity("Domain.Models.Appointment", b =>
                {
                    b.HasOne("Domain.Models.BloodRequest", "BloodRequest")
                        .WithMany("Appointments")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Donor", "Donor")
                        .WithMany("Appointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.HasOne("Domain.Models.Requester", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Models.Donor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
