// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    [Migration("20260224023053_Updated entities and new dataseed")]
    partial class Updatedentitiesandnewdataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("DonorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodRequestId = 1,
                            CancellationToken = "meVuNSBc1w5v88fPCg28+h5qzlysU8S2pFkQE7lY/RI=",
                            DonorId = 1,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 2,
                            BloodRequestId = 1,
                            CancellationToken = "1Srh18AcS+fqMjjLHT1+7X5H9fWLVxFJpifGz8HLhKI=",
                            DonorId = 2,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 3,
                            BloodRequestId = 4,
                            CancellationToken = "ERF66vtnfDQNma/WWdEzoNAKfRyWHIqG8xHxrTUfKrU=",
                            DonorId = 3,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 4,
                            BloodRequestId = 2,
                            CancellationToken = "E6qU8tnkXSE3u5Sy+INDlZEYEQwDVIceHMF0O2fdDTY=",
                            DonorId = 4,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 5,
                            BloodRequestId = 2,
                            CancellationToken = "o7yR2/5M30r5Qc19VT2oPdEH65v6LoRPu9s3PJ05HHQ=",
                            DonorId = 5,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 6,
                            BloodRequestId = 3,
                            CancellationToken = "aU9sOGEOA/+KMHjfEIg7L8DbN3RKCdRin7rM3qIY2Qw=",
                            DonorId = 1,
                            IsCancelled = true
                        },
                        new
                        {
                            Id = 7,
                            BloodRequestId = 8,
                            CancellationToken = "vb//68t0hDlHgjJDDFNQcO8wqTNzDqRAtf4PU4FHhgM=",
                            DonorId = 2,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 8,
                            BloodRequestId = 10,
                            CancellationToken = "SgurdbJg/5s8fz8FSQnTmFr9FnGj0HMTevLko1AV1I8=",
                            DonorId = 4,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 9,
                            BloodRequestId = 7,
                            CancellationToken = "gWhxgQ5W9Ocy5lxwUiA/lQwvW4qxJ222SZq/I86Ci78=",
                            DonorId = 5,
                            IsCancelled = false
                        },
                        new
                        {
                            Id = 10,
                            BloodRequestId = 4,
                            CancellationToken = "HGSq9wAozxcR6czCNWKncUp/ygKII2w8TJDuIjF5d4o=",
                            DonorId = 2,
                            IsCancelled = true
                        });
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("BloodTypesNeeded")
                        .HasColumnType("integer[]");

                    b.Property<int>("RemainingUnits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("BloodRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 7, 6 },
                            RemainingUnits = 3,
                            RequestDate = new DateTime(2026, 2, 26, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5872),
                            RequestStatus = 0,
                            RequesterId = 3,
                            TargetUnits = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 0 },
                            RemainingUnits = 0,
                            RequestDate = new DateTime(2026, 2, 23, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5891),
                            RequestStatus = 1,
                            RequesterId = 3,
                            TargetUnits = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Virasoro 1249, Rosario",
                            BloodTypesNeeded = new[] { 3, 5 },
                            RemainingUnits = 10,
                            RequestDate = new DateTime(2026, 3, 1, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5893),
                            RequestStatus = 0,
                            RequesterId = 4,
                            TargetUnits = 10
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bv. Oroño 860, Rosario",
                            BloodTypesNeeded = new[] { 6 },
                            RemainingUnits = 1,
                            RequestDate = new DateTime(2026, 2, 25, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5897),
                            RequestStatus = 0,
                            RequesterId = 5,
                            TargetUnits = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "San Luis 2450, Rosario",
                            BloodTypesNeeded = new[] { 1 },
                            RemainingUnits = 4,
                            RequestDate = new DateTime(2026, 3, 6, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5899),
                            RequestStatus = 0,
                            RequesterId = 7,
                            TargetUnits = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 7 },
                            RemainingUnits = 2,
                            RequestDate = new DateTime(2026, 2, 24, 7, 30, 53, 616, DateTimeKind.Utc).AddTicks(5901),
                            RequestStatus = 0,
                            RequesterId = 3,
                            TargetUnits = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "Virasoro 1249, Rosario",
                            BloodTypesNeeded = new[] { 2 },
                            RemainingUnits = 0,
                            RequestDate = new DateTime(2026, 2, 19, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5903),
                            RequestStatus = 1,
                            RequesterId = 4,
                            TargetUnits = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "Bv. Oroño 860, Rosario",
                            BloodTypesNeeded = new[] { 6, 0 },
                            RemainingUnits = 6,
                            RequestDate = new DateTime(2026, 2, 27, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5905),
                            RequestStatus = 0,
                            RequesterId = 5,
                            TargetUnits = 6
                        },
                        new
                        {
                            Id = 9,
                            Address = "Pellegrini 3205, Rosario",
                            BloodTypesNeeded = new[] { 4 },
                            RemainingUnits = 8,
                            RequestDate = new DateTime(2026, 2, 14, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5907),
                            RequestStatus = 2,
                            RequesterId = 3,
                            TargetUnits = 8
                        },
                        new
                        {
                            Id = 10,
                            Address = "San Luis 2450, Rosario",
                            BloodTypesNeeded = new[] { 7 },
                            RemainingUnits = 2,
                            RequestDate = new DateTime(2026, 3, 11, 2, 30, 53, 616, DateTimeKind.Utc).AddTicks(5909),
                            RequestStatus = 0,
                            RequesterId = 7,
                            TargetUnits = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan.perez@example.com",
                            Name = "Juan Pérez",
                            Phone = "3411234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.garcia@example.com",
                            Name = "María García",
                            Phone = "3417654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.lopez@example.com",
                            Name = "Carlos López",
                            Phone = "1198765432"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.mtz@example.com",
                            Name = "Ana Martínez",
                            Phone = "3415554443"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lucia.f@example.com",
                            Name = "Lucía Fernández",
                            Phone = "3410009998"
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "heca@example.com",
                            IsActive = true,
                            Name = "Hospital Emergencias Clemente Álvarez",
                            Password = "$2a$11$bClCfIUOiNSwX1dpvOTOK.iPTP/kLv0ehTjZ6evDIY0FyLXkjStce",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "italiano@example.com",
                            IsActive = true,
                            Name = "Hospital Italiano",
                            Password = "$2a$11$JAUJ4IHItkKYeEhbMKLTeOZaRI1Mw3c5VM/SezHnvAysce6I5sAfm",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "parque@example.com",
                            IsActive = true,
                            Name = "Sanatorio Parque",
                            Password = "$2a$11$AyyhcGe518dZjgM0rnplKuj/AsOv/Adjpn2l.1ENL1wnu.ehh7zmu",
                            Role = "Requester",
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "centenario@example.com",
                            IsActive = true,
                            Name = "Hospital Centenario",
                            Password = "$2a$11$su/RbxD6q776KyBXkU9HbOINKE.GbdL5DkdkoXB.w.pITz3ffmznW",
                            Role = "Requester",
                            AdmissionStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            Email = "clinica@example.com",
                            IsActive = true,
                            Name = "Clínica de la Mujer",
                            Password = "$2a$11$x8BtOik9PZV0CCIoqOzzZu4n1PPGHh3POameGvekd.SZMLCvieVk6",
                            Role = "Requester",
                            AdmissionStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Staff", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "Admin",
                            Password = "$2a$11$fq5.Vt0fX7eNqZRQkpSymu.knpL90erYskefe.h5ml6Eed65XBP12",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mod@example.com",
                            IsActive = true,
                            Name = "Moderador",
                            Password = "$2a$11$EKinuHg6XFRxS9aU6vnNtepk8mqJb3YaxZs9S4PEP.McobDDbPvs6",
                            Role = "Moderator"
                        });
                });

            modelBuilder.Entity("Domain.Models.Appointment", b =>
                {
                    b.HasOne("Domain.Models.BloodRequest", "BloodRequest")
                        .WithMany("Appointments")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Donor", "Donor")
                        .WithMany("Appointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.HasOne("Domain.Models.Requester", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Models.Donor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
