// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    [Migration("20260220222725_Added blood request")]
    partial class Addedbloodrequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("BloodTypesNeeded")
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("FulfilledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RemainingUnits")
                        .HasColumnType("integer");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("Domain.Models.Donator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Donator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gabriel@mail.com",
                            Name = "Gabriel",
                            Phone = "1234567890123"
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "gruppesechs@mail.com",
                            IsActive = true,
                            Name = "Gruppe Sechs",
                            Password = "$2a$11$R8sf7vX7CFFmkLXzZAJsDOSmyfxnCQ6IGDHQiwtyOzrmfiidOdvWW",
                            Role = "Requester",
                            AdmissionStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Staff", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            IsActive = true,
                            Name = "admin",
                            Password = "$2a$11$8SI9SHMLUK.rA3NbiY0BquE0tjdYSmzUppMVv2x2INUdUxkF41.3O",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mod",
                            IsActive = true,
                            Name = "mod",
                            Password = "$2a$11$4j2Ds7Oy3TnGHd4RSfGatOJr4/nk05ag.THPT07B/bAyDUgGEYRni",
                            Role = "Moderator"
                        });
                });

            modelBuilder.Entity("Domain.Models.BloodRequest", b =>
                {
                    b.HasOne("Domain.Models.Requester", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");
                });
#pragma warning restore 612, 618
        }
    }
}
