// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    [Migration("20260219014007_Added role to requesters")]
    partial class Addedroletorequesters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Donator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Donator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gabriel@mail.com",
                            Name = "Gabriel",
                            Phone = "1234567890123"
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "gruppesechs@mail.com",
                            IsActive = true,
                            Name = "Gruppe Sechs",
                            Password = "$2a$11$Nl43Whql4pHjRmDEB5PhiesmRrULEZ1hKNxz/Wyz5kx0oeLLJT/Lm",
                            Role = 0,
                            AdmissionStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Staff", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            IsActive = true,
                            Name = "admin",
                            Password = "$2a$11$lGqHZpIqPENUqZsFTZmh9uNDs7XZoTSjmc6QASBHrrHuDcP0LACba",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "mod",
                            IsActive = true,
                            Name = "mod",
                            Password = "$2a$11$mkJkDilJmtOa6..QOdjrSeN.LOGxfaI97dbINaMkcggY9RbffzKm6",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
